from wtforms import Form, StringField, SelectField

class Forms(Form):
    escolha = [('João Pessoa', 'João Pessoa'),
               ('Campina Grande', 'Campina Grande'),
               ('Santa Rita', 'Santa Rita'),
               ('Patos','Patos'),
               ('Bayeux','Bayeux'),
               ('Souza','Souza'),
               ('Cabedelo','Cabedelo'),
               ('Cajazeiras','Cajazeiras'),
               ('Guarabira','Guarabira'),
               ('Sapé','Sapé'),
               ('Queimadas','Queimadas'),
               ('Mamanguape','Mamanguape'),
               ('Pombal','Pombal'),
               ('Monteiro','Monteiro'),
               ('São Bento','São Bento'),
               ('Esperança','Esperança'),
               ('Catolé do Rocha','Catolé do Rocha'),
               ('Pedras de Fogo','Pedras de Fogo'),
               ('Lagoa Seca','Lagoa Seca'),
               ('Conde','Conde'),
               ('Solânea','Solânea'),
               ('Alagoa Grande','Alagoa Grande'),
               ('Itaporanga','Itaporanga'),
               ('Rio Tinto','Rio Tinto'),
               ('Itabaiana','Itabaiana'),
               ('Bananeiras','Bananeiras'),
               ('Areia','Areia'),
               ('Alhandra','Alhandra'),
               ('Caaporã','Caaporã'),
               ('Mari','Mari'),
               ('Princesa Isabel','Princesa Isabel'),
               ('Alagoa Nova','Alagoa Nova'),
               ('Cuité','Cuité'),
               ('São josé de Piranhas','São josé de Piranhas'),
               ('Aroeiras','Aroeiras'),
               ('Itapororoca','Itapororoca'),
               ('Picuí','Picuí'),
               ('Conceição','Conceição'),
               ('Remígio','Remígio'),
               ('Pirimbu','Pirimbu'),
               ('Ingá','Ingá'),
               ('São João do Rio do Peixe','São João do Rio do Peixe'),
               ('Boqueirão','Boqueirão'),
               ('Pocinhos','Pocinhos'),
               ('Araruna','Araruna'),
               ('Juazeirinho','Juazeirinho'),
               ('Cruz do Espírito Santo','Cruz do Espírito Santo'),
               ('Araçagi','Araçagi'),
               ('Sumé','Sumé'),
               ('Piancó','Piancó')
               ]
    filter = SelectField('oque proucura?:', choices=escolha)
    search = StringField('')
